# SPDX-License-Identifier: MIT

from m1n1.utils import *

class R_ATCPHY_USB2PHY_USBCTL(Register32):
    MODE_HOST = 1
    MODE_ISOLATION = 2


class R_ATCPHY_USB2PHY_CTL(Register32):
    RESET = 0
    PORT_RESET = 1
    APB_RESETN = 2
    SIDDQ = 3


class R_ATCPHY_USB2PHY_SIG(Register32):
    VBUSDET_FORCE_VAL = 0
    VBUSDET_FORCE_EN = 1
    VBUSVLDEXT_FORCE_VAL = 2
    VBUSVLDEXT_FORCE_EN = 3
    MODE_HOST = 12 + 7, 12


class R_ATCPHY_USB2PHY_MISCTUNE(Register32):
    APBCLK_GATE_OFF = 29
    REFCLK_GATE_OFF = 30


class PhyRegs(RegMap):
    USB2PHY_USBCTL = 0x00, R_ATCPHY_USB2PHY_USBCTL
    USB2PHY_CTL = 0x04, R_ATCPHY_USB2PHY_CTL
    USB2PHY_SIG = 0x08, R_ATCPHY_USB2PHY_SIG
    USB2PHY_MISCTUNE = 0x1C, R_ATCPHY_USB2PHY_MISCTUNE
