# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install aarch64-linux-gnu- toolchain
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y gcc-aarch64-linux-gnu

      - name: Install nightly rust
        run: |
          export RUSTUP_TOOLCHAIN=stable
          rustup target install aarch64-unknown-none-softfloat

      - name: Build
        run: make -k -j2 ARCH=aarch64-linux-gnu- CHAINLOADING=1

      - uses: actions/upload-artifact@v4
        with:
          name: m1n1
          path: |
            build/m1n1.macho
            build/m1n1.bin
