# This is a basic workflow to help you get started with Actions

name: format-check

# Controls when the action will run. 
on: [ push, pull_request, workflow_dispatch ]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install nightly rust
        run: |
          rm -f ~/.cargo/bin/rustfmt
          rm -f ~/.cargo/bin/cargo-fmt
          rustup toolchain install nightly --component rustfmt --component clippy --allow-downgrade

      - name: Run format-check
        run: |
          make format-check
          make rustfmt-check
